### ISSUE TITLE
Fork is not functional

### ISSUE THREAD

**Issue by mariusrugan** [geek-cookbook/charts#3]
### Helm chart name

Any

### Describe the solution you'd like

Hi,
As per README 

```
helm repo add geek-cookbook https://geek-cookbook.com/charts/
```

```
Error: looks like "https://geek-cookbook.com/charts/" is not a valid chart repository or cannot be reached: Get "https://geek-cookbook.com/charts/index.yaml": x509: “*.kasserver.com” certificate name does not match input
```

also 
```
Error: looks like "https://library-charts.geek-cookbook.com" is not a valid chart repository or cannot be reached: Get "https://library-charts.geek-cookbook.com/index.yaml": x509: “*.kasserver.com” certificate name does not match input
```
(referenced for example in https://github.com/geek-cookbook/charts/blob/main/charts/stable/nullserv/Chart.yaml)

Also, you need to fork (this is the base layer chart)
```
https://github.com/k8s-at-home/library-charts
```

**Comment by funkypenguin** [comment]
Thanks @mariusrugan, I've spent some time getting CI resources going, and am now working on bringing all the workflows back to life :) Watch this space!

**Comment by funkypenguin** [comment]
Woo, I think I've got it in a working state now. I'd love to add some improvements, like having renovatebot auto-bump chart / app versions on upstream updates, but for now, it works like the k8s-at-home repo does!
